--------------------------------------------------------
--  File created - Tuesday-December-19-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FEEDBACK
--------------------------------------------------------

  CREATE TABLE "PATTERSON.A"."FEEDBACK" 
   (	"FEEDBACK_ID" NUMBER, 
	"EMAIL" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"QUERY1" NUMBER(1,0), 
	"QUERY2" NUMBER(1,0), 
	"QUERY3" NUMBER(1,0), 
	"QUERY4" NUMBER(1,0), 
	"QUERY5" NUMBER(1,0), 
	"FEEDBACK" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("FEEDBACK") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into "PATTERSON.A".FEEDBACK
SET DEFINE OFF;
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (22,'jilljj@gmail.com','Jill Jillferson',1,0,0,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (23,'jilljj@gmail.com','Jill Jillferson',0,0,1,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (25,'a@gmail.com','sdasd',1,0,0,0,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (26,'a@gmail.com','sdasd',1,0,0,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (27,'a@gmail.com','sdasd',0,0,0,0,1);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (28,'a@gmail.com','sdasd',1,0,0,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (29,'a@gmail.com','sdasd',0,1,0,0,1);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (30,'a@gmail.com','sdasd',0,1,0,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (31,'a@gmail.com','sdfsdf',1,0,0,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (34,'Fak@gmail.com','John Smoth',0,0,0,0,1);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (24,'jilljj@gmail.com','Jill Jillferson',1,0,0,1,0);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (33,'donatee1@gmail.com','fdfd',1,1,0,1,1);
Insert into "PATTERSON.A".FEEDBACK (FEEDBACK_ID,EMAIL,NAME,QUERY1,QUERY2,QUERY3,QUERY4,QUERY5) values (32,'g@hhmcv.com','New Guy',0,1,1,0,1);
--------------------------------------------------------
--  Constraints for Table FEEDBACK
--------------------------------------------------------

  ALTER TABLE "PATTERSON.A"."FEEDBACK" MODIFY ("FEEDBACK_ID" NOT NULL ENABLE);
