WITH PERCENTILES AS (
    SELECT 
        YEAR, 
        PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY SALARY ASC) AS "25PERCENTILE",
        PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY SALARY ASC) AS "75PERCENTILE"
    FROM 
        PLAYSFORATEAM 
    GROUP BY 
        YEAR
), PLAYER_STATS AS (
    SELECT 
        P.YEAR, 
        PLAYSFORATEAM.PLAYER_ID, 
        BATTINGSEASON.R AS RUNS, 
        (BATTINGSEASON.AB - BATTINGSEASON.H + BATTINGSEASON.CS + BATTINGSEASON.SH + BATTINGSEASON.SF + BATTINGSEASON.GIDP) AS OUTS,
        CASE 
            WHEN PLAYSFORATEAM.SALARY < P."25PERCENTILE" THEN 'LOW'
            WHEN PLAYSFORATEAM.SALARY < P."75PERCENTILE" AND PLAYSFORATEAM.SALARY > P."25PERCENTILE" THEN 'MID'
            ELSE 'HIGH'
        END AS SALARY_QUARTILE
    FROM 
        PERCENTILES P
    INNER JOIN 
        PLAYSFORATEAM ON P.YEAR = PLAYSFORATEAM.YEAR 
    INNER JOIN 
        BATTINGSEASON ON P.YEAR = BATTINGSEASON.YEAR AND PLAYSFORATEAM.PLAYER_ID = BATTINGSEASON.PLAYER_ID
    WHERE 
        BATTINGSEASON.R > 0 AND PLAYSFORATEAM.SALARY IS NOT NULL
)

SELECT 
    YEAR, 
    ROUND(AVG(CASE WHEN SALARY_QUARTILE = 'LOW' THEN RUNS/NULLIF(OUTS,0) END), 8) AS LOW,
    ROUND(AVG(CASE WHEN SALARY_QUARTILE = 'MID' THEN RUNS/NULLIF(OUTS,0) END), 8) AS MID,
    ROUND(AVG(CASE WHEN SALARY_QUARTILE = 'HIGH' THEN RUNS/NULLIF(OUTS,0) END), 8) AS HIGH
FROM 
    PLAYER_STATS
WHERE 
    OUTS > 0 AND YEAR >= :startYear AND YEAR <= :endYear 
GROUP BY 
    YEAR
ORDER BY 
    YEAR ASC
